"use client";

import Head from "next/head";
import { Cabin } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { IoChatboxEllipses } from "react-icons/io5";
import ChatBot from "@/components/Chats";
import { useState } from "react";

const inter = Cabin({ subsets: ["latin"] });

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const [openChatBot, setOpenChatBot] = useState<boolean>(false);

  const handleOpenChatBot = () => {
    setOpenChatBot(!openChatBot);
  };

  return (
    <html lang="en">
      <Head>
        <title>OurMart</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        {/* Header */}
        <Header />
        <div className="flex">
          {modal}
          {children}
        </div>
        <div
          className="fixed right-8 bottom-8 p-3 flex flex-col justify-center items-center"
          onClick={handleOpenChatBot}
        >
          <IoChatboxEllipses className="text-5xl text-gray-700 text-bold" />
          <span className="text-sm font-medium text-black">Need Help</span>
        </div>
        {openChatBot && (
          <div className="">
            <ChatBot
              openChatBot={openChatBot}
              setOpenChatBot={setOpenChatBot}
            />
          </div>
        )}
      </body>
    </html>
  );
}
